/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedQuizzesRouteImport } from './routes/_authenticated/quizzes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBuilderRouteImport } from './routes/_authenticated/builder'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedQuizIdRouteImport } from './routes/_authenticated/quiz.$id'
import { Route as AuthenticatedQuizzesIdVersionsRouteImport } from './routes/_authenticated/quizzes.$id.versions'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizzesRoute = AuthenticatedQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuilderRoute = AuthenticatedBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizIdRoute = AuthenticatedQuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizzesIdVersionsRoute =
  AuthenticatedQuizzesIdVersionsRouteImport.update({
    id: '/$id/versions',
    path: '/$id/versions',
    getParentRoute: () => AuthenticatedQuizzesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/quizzes': typeof AuthenticatedQuizzesRouteWithChildren
  '/results': typeof AuthenticatedResultsRoute
  '/review': typeof AuthenticatedReviewRoute
  '/quiz/$id': typeof AuthenticatedQuizIdRoute
  '/quizzes/$id/versions': typeof AuthenticatedQuizzesIdVersionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/quizzes': typeof AuthenticatedQuizzesRouteWithChildren
  '/results': typeof AuthenticatedResultsRoute
  '/review': typeof AuthenticatedReviewRoute
  '/quiz/$id': typeof AuthenticatedQuizIdRoute
  '/quizzes/$id/versions': typeof AuthenticatedQuizzesIdVersionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/builder': typeof AuthenticatedBuilderRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/quizzes': typeof AuthenticatedQuizzesRouteWithChildren
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/quiz/$id': typeof AuthenticatedQuizIdRoute
  '/_authenticated/quizzes/$id/versions': typeof AuthenticatedQuizzesIdVersionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/builder'
    | '/dashboard'
    | '/quizzes'
    | '/results'
    | '/review'
    | '/quiz/$id'
    | '/quizzes/$id/versions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/builder'
    | '/dashboard'
    | '/quizzes'
    | '/results'
    | '/review'
    | '/quiz/$id'
    | '/quizzes/$id/versions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/builder'
    | '/_authenticated/dashboard'
    | '/_authenticated/quizzes'
    | '/_authenticated/results'
    | '/_authenticated/review'
    | '/_authenticated/quiz/$id'
    | '/_authenticated/quizzes/$id/versions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes': {
      id: '/_authenticated/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AuthenticatedQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/$id': {
      id: '/_authenticated/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof AuthenticatedQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes/$id/versions': {
      id: '/_authenticated/quizzes/$id/versions'
      path: '/$id/versions'
      fullPath: '/quizzes/$id/versions'
      preLoaderRoute: typeof AuthenticatedQuizzesIdVersionsRouteImport
      parentRoute: typeof AuthenticatedQuizzesRoute
    }
  }
}

interface AuthenticatedQuizzesRouteChildren {
  AuthenticatedQuizzesIdVersionsRoute: typeof AuthenticatedQuizzesIdVersionsRoute
}

const AuthenticatedQuizzesRouteChildren: AuthenticatedQuizzesRouteChildren = {
  AuthenticatedQuizzesIdVersionsRoute: AuthenticatedQuizzesIdVersionsRoute,
}

const AuthenticatedQuizzesRouteWithChildren =
  AuthenticatedQuizzesRoute._addFileChildren(AuthenticatedQuizzesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBuilderRoute: typeof AuthenticatedBuilderRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedQuizzesRoute: typeof AuthenticatedQuizzesRouteWithChildren
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedQuizIdRoute: typeof AuthenticatedQuizIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBuilderRoute: AuthenticatedBuilderRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedQuizzesRoute: AuthenticatedQuizzesRouteWithChildren,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedQuizIdRoute: AuthenticatedQuizIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
